import AppProvider from "@/app-provider";
import { DefaultLayout } from "@/components/layout/default-layout";
import { decodeJWT } from "@/lib/utils";
import { AntdRegistry } from "@ant-design/nextjs-registry";
import type { Metadata } from "next";
import { cookies } from "next/headers";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import "./globals.css";

export type User = {
  name: string;
  email: string;
  role: string;
  tenant: string;
  sub: string;
  jti: string;
  iat: number;
  nbf: number;
  exp: number;
  iss: string;
  aud: string;
};
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cookieStore = cookies();
  const accessToken = cookieStore.get("accessToken");
  let user: User | null = null;
  if (!accessToken) {
    user = null;
  } else {
    user = decodeJWT(accessToken.value);
  }
  return (
    <html lang="en">
      <body suppressHydrationWarning={true} className="font-visby bg-[#f5f5f5]">
        <AntdRegistry>
          <AppProvider user={user} inititalSessionToken={accessToken?.value}>
            <ToastContainer />
            <DefaultLayout user={user}>{children}</DefaultLayout>
          </AppProvider>
        </AntdRegistry>
      </body>
    </html>
  );
}
