import Sidebar from "@/components/layout/Sidebar";
import TopBar from "@/components/layout/Topbar";
import { AntdRegistry } from "@ant-design/nextjs-registry";
import type { Metadata } from "next";
import { cookies } from "next/headers";
import { ToastContainer, toast } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import "./globals.css";
import AppProvider from "@/app-provider";
import { DefaultLayout } from "@/components/layout/default-layout";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cookieStore = cookies();
  const accessToken = cookieStore.get("accessToken");
  let user: any = null;
  if (accessToken) {
    // const data = await accountApiRequest.me(sessionToken.value)
    user = true;
  }
  return (
    <html lang="en">
      <body suppressHydrationWarning={true} className="font-visby bg-[#f5f5f5]">
        <AntdRegistry>
          <AppProvider user={user} inititalSessionToken={accessToken?.value}>
            <ToastContainer />
            <DefaultLayout user={user}>{children}</DefaultLayout>
          </AppProvider>
        </AntdRegistry>
      </body>
    </html>
  );
}
